import { supabase, type SupabaseSession } from './supabase';
import { applyTranslation, formatAuthorByline, getPostAuthors, isPostPublic, JOURNAL_SELECT, type JournalAuthor, type JournalPost, type JournalStatus, type PublicJournalPost } from './journal';

export type BreakTheCircleMeta = { id: string; journal_post_id: string; cta_label?: string | null; cta_url?: string | null; featured_order: number | null; is_featured: boolean; created_by?: string; updated_by?: string; created_at?: string; updated_at?: string; journal_posts?: JournalPost | null };
export type BreakTheCirclePost = PublicJournalPost & { break_the_circle_posts?: BreakTheCircleMeta[]; btcMeta?: BreakTheCircleMeta | null };
export type BreakTheCircleForm = { id?: string; title: string; slug: string; subtitle: string; excerpt: string; body: string; content_format: 'markdown' | 'rich_text' | 'video' | 'mixed'; original_language: string; cover_image_url: string; cover_image_alt: string; author_ids: string[]; tag_ids: string[]; reading_time_minutes: number; status: JournalStatus; published_at: string; scheduled_for: string; is_featured: boolean; featured_order: number; cta_label: string; cta_url: string; seo_title: string; seo_description: string; og_image_url: string; };

const BTC_SLUG = 'help-us-break-the-circle';
const BTC_SELECT = `${JOURNAL_SELECT},break_the_circle_posts!inner(*)`;
const ADMIN_SELECT = `*,journal_posts(${JOURNAL_SELECT})`;

function readJson<T>(responseOrPromise: Response | Promise<Response>): Promise<T> { return Promise.resolve(responseOrPromise).then(async (response) => { if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<T>; }); }
function esc(v: string) { return encodeURIComponent(v); }
export function isAdminSession(session?: SupabaseSession | null) { const role = (session?.user as { app_metadata?: { role?: string }, user_metadata?: { role?: string } } | undefined)?.app_metadata?.role || (session?.user as { user_metadata?: { role?: string } } | undefined)?.user_metadata?.role; return role === 'admin'; }
export function requireAdminSession(session?: SupabaseSession | null) { if (!session?.access_token) throw new Error('Sign in as an administrator to manage Break the Circle posts.'); if (!isAdminSession(session)) throw new Error('Administrator access is required.'); return session; }
export function normalizeSlug(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
export function validateBreakTheCircleForm(input: BreakTheCircleForm, existingSlug?: string) { const errors: Record<string,string> = {}; const slug = normalizeSlug(input.slug); if (!input.title.trim()) errors.title = 'Title is required.'; if (!slug) errors.slug = 'Slug is required.'; if (slug && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) errors.slug = 'Use a URL-safe slug with lowercase letters, numbers and hyphens.'; if (input.status === 'published' || input.status === 'scheduled') { if (!input.body.trim()) errors.body = 'Body is required before publishing or scheduling.'; if (!input.excerpt.trim()) errors.excerpt = 'Excerpt is required before publishing or scheduling.'; }
  if (input.cover_image_url.trim() && !input.cover_image_alt.trim()) errors.cover_image_alt = 'Cover image alt text is required when a cover image is set.';
  if (input.status === 'scheduled') { const t = Date.parse(input.scheduled_for); if (!input.scheduled_for || Number.isNaN(t) || t <= Date.now()) errors.scheduled_for = 'Scheduled posts require a future scheduled date.'; }
  if (input.status === 'published') { const t = Date.parse(input.published_at); if (!input.published_at || Number.isNaN(t)) errors.published_at = 'Published posts require a valid publication date.'; }
  if (Boolean(input.cta_label.trim()) !== Boolean(input.cta_url.trim())) errors.cta = 'CTA label and URL must either both be filled in or both be empty.';
  if (input.cta_url.trim()) { try { new URL(input.cta_url); } catch { errors.cta_url = 'Enter a valid CTA URL.'; } }
  if (input.featured_order < 0) errors.featured_order = 'Featured order must be zero or greater.';
  if (input.seo_title.length > 70) errors.seo_title = 'SEO title should be 70 characters or fewer.';
  if (input.seo_description.length > 170) errors.seo_description = 'SEO description should be 170 characters or fewer.';
  if (existingSlug && slug !== existingSlug && !slug) errors.slug = 'Slug is required.';
  return errors; }
export const emptyBreakTheCircleForm: BreakTheCircleForm = { title:'', slug:'', subtitle:'', excerpt:'', body:'', content_format:'markdown', original_language:'en', cover_image_url:'', cover_image_alt:'', author_ids:[], tag_ids:[], reading_time_minutes:4, status:'draft', published_at:'', scheduled_for:'', is_featured:false, featured_order:0, cta_label:'', cta_url:'', seo_title:'', seo_description:'', og_image_url:'' };
export function formFromPost(post?: JournalPost | null, meta?: BreakTheCircleMeta | null): BreakTheCircleForm { return { ...emptyBreakTheCircleForm, id: post?.id, title: post?.title || '', slug: post?.slug || '', subtitle: post?.subtitle || '', excerpt: post?.excerpt || '', body: post?.body || '', content_format: post?.content_format || 'markdown', original_language: post?.original_language || 'en', cover_image_url: post?.cover_image_url || '', cover_image_alt: post?.cover_image_alt || '', author_ids: (post?.journal_post_author_links || []).map((l)=>l.journal_authors?.id).filter(Boolean) as string[], tag_ids: (post?.journal_post_tags || []).map((t)=>t.journal_tags?.id).filter(Boolean) as string[], reading_time_minutes: post?.reading_time_minutes || 4, status: post?.status || 'draft', published_at: post?.published_at || '', scheduled_for: post?.scheduled_for || '', is_featured: Boolean(meta?.is_featured), featured_order: meta?.featured_order || 0, cta_label: meta?.cta_label || '', cta_url: meta?.cta_url || '', seo_title: post?.seo_title || '', seo_description: post?.seo_description || '', og_image_url: post?.og_image_url || '' }; }
function withMeta(row: JournalPost & { break_the_circle_posts?: BreakTheCircleMeta[] }): BreakTheCirclePost { const p = applyTranslation(row) as BreakTheCirclePost; p.btcMeta = row.break_the_circle_posts?.[0] || null; return p; }
export function sortFeaturedBreakTheCircle(posts: BreakTheCirclePost[]) { return [...posts].sort((a,b)=>(a.btcMeta?.featured_order ?? 999)-(b.btcMeta?.featured_order ?? 999) || Date.parse(b.published_at || '')-Date.parse(a.published_at || '')); }
export function filterAdminBreakTheCirclePosts(posts: BreakTheCirclePost[], opts: { search?: string; status?: string; featured?: string }) { const q=(opts.search||'').toLowerCase().trim(); return posts.filter((p)=>(!opts.status||opts.status==='all'||p.status===opts.status)&&(!opts.featured||opts.featured==='all'||(opts.featured==='featured'?p.btcMeta?.is_featured:!p.btcMeta?.is_featured))&&(!q||[p.title,p.slug,p.excerpt].filter(Boolean).join(' ').toLowerCase().includes(q))); }
export async function getBreakTheCirclePublicIndex() { const query = `select=${BTC_SELECT}&journal_categories.slug=eq.${BTC_SLUG}&status=eq.published&published_at=not.is.null&published_at=lte.${esc(new Date().toISOString())}&order=published_at.desc`; const rows = await readJson<(JournalPost & { break_the_circle_posts?: BreakTheCircleMeta[] })[]>(supabase.from('journal_posts').request({ query })); const posts=rows.filter((p)=>isPostPublic(p)).map(withMeta); return { posts, featured: sortFeaturedBreakTheCircle(posts.filter((p)=>p.btcMeta?.is_featured)), latest: posts } }
export async function getBreakTheCirclePublicPost(slug: string) { const query = `select=${BTC_SELECT}&slug=eq.${esc(slug)}&status=eq.published&published_at=not.is.null&published_at=lte.${esc(new Date().toISOString())}`; const rows = await readJson<(JournalPost & { break_the_circle_posts?: BreakTheCircleMeta[] })[]>(supabase.from('journal_posts').request({ query })); const row = rows.find((p)=>p.slug===slug&&isPostPublic(p)); return row ? withMeta(row) : null; }
export async function getAdminBreakTheCirclePosts(session: SupabaseSession) { requireAdminSession(session); const rows = await readJson<BreakTheCircleMeta[]>(supabase.from('break_the_circle_posts').request({ query: `select=${ADMIN_SELECT}&order=updated_at.desc`, accessToken: session.access_token })); return rows.map((r)=>{ const p=applyTranslation(r.journal_posts!) as BreakTheCirclePost; p.btcMeta=r; return p; }); }
export async function getAdminBreakTheCirclePost(id: string, session: SupabaseSession) { requireAdminSession(session); const rows = await readJson<BreakTheCircleMeta[]>(supabase.from('break_the_circle_posts').request({ query: `select=${ADMIN_SELECT}&journal_post_id=eq.${esc(id)}`, accessToken: session.access_token })); return rows[0] || null; }
export async function getEditorOptions(session: SupabaseSession) { requireAdminSession(session); const [authors,tags] = await Promise.all([readJson<JournalAuthor[]>(supabase.from('journal_authors').request({query:'select=*&order=display_name.asc', accessToken:session.access_token})), readJson<{id:string;name:string;slug:string}[]>(supabase.from('journal_tags').request({query:'select=id,name,slug&order=name.asc', accessToken:session.access_token}))]); return { authors, tags }; }
function payload(input: BreakTheCircleForm) { const now=new Date().toISOString(); return { slug: normalizeSlug(input.slug), status: input.status, title: input.title.trim(), subtitle: input.subtitle.trim() || null, excerpt: input.excerpt.trim() || null, body: input.body.trim() || null, content_format: input.content_format, cover_image_url: input.cover_image_url.trim() || null, cover_image_alt: input.cover_image_alt.trim() || null, original_language: input.original_language || 'en', is_featured: input.is_featured, published_at: input.status === 'published' ? (input.published_at || now) : (input.published_at || null), scheduled_for: input.status === 'scheduled' ? input.scheduled_for : null, reading_time_minutes: input.reading_time_minutes || null, seo_title: input.seo_title.trim() || null, seo_description: input.seo_description.trim() || null, og_image_url: input.og_image_url.trim() || null, updated_at: now }; }
export async function saveBreakTheCirclePost(input: BreakTheCircleForm, session: SupabaseSession) { requireAdminSession(session); const errors=validateBreakTheCircleForm(input); if (Object.keys(errors).length) throw new Error(Object.values(errors)[0]); const body={ p_post_id: input.id || null, p_post: payload(input), p_meta: { cta_label: input.cta_label.trim() || null, cta_url: input.cta_url.trim() || null, is_featured: input.is_featured, featured_order: input.featured_order || 0, updated_by: session.user.id, ...(input.id ? {} : { created_by: session.user.id }) }, p_author_ids: input.author_ids, p_tag_ids: input.tag_ids, p_category_slug: BTC_SLUG }; const rows = await readJson<{ id: string }[]>(supabase.rpc('upsert_break_the_circle_post', body, session.access_token)); return rows[0]?.id || input.id; }
export async function transitionBreakTheCirclePost(id: string, status: JournalStatus, session: SupabaseSession, scheduled_for?: string) { requireAdminSession(session); const now=new Date().toISOString(); const body: Record<string, unknown> = { status, updated_at: now }; if (status==='published') { body.published_at = now; body.scheduled_for = null; } if (status==='scheduled') { const scheduledAt = Date.parse(scheduled_for || ''); if (!scheduled_for || Number.isNaN(scheduledAt) || scheduledAt <= Date.now()) throw new Error('Scheduled posts require a future scheduled date.'); body.scheduled_for = scheduled_for; body.published_at = null; } if (status==='draft' || status==='archived') { body.scheduled_for=null; if (status==='draft') body.published_at=null; } await readJson(supabase.from('journal_posts').request({ method:'PATCH', query:`id=eq.${esc(id)}`, accessToken:session.access_token, body })); }
export async function deleteBreakTheCirclePost(id: string, session: SupabaseSession) { requireAdminSession(session); await readJson(supabase.from('journal_posts').request({ method:'DELETE', query:`id=eq.${esc(id)}`, accessToken:session.access_token })); }
export { formatAuthorByline, getPostAuthors };
