import { supabase, type SupabaseSession } from './supabase';

export type JournalStatus = 'draft' | 'scheduled' | 'published' | 'archived';
export type ContentFormat = 'markdown' | 'rich_text' | 'video' | 'mixed';
export type TranslationStatus = 'draft' | 'review' | 'published' | 'archived';
export type JournalCategory = { id: string; name: string; slug: string; description?: string; display_order: number; is_public: boolean; created_at: string; updated_at: string; };
export type JournalTag = { id: string; name: string; slug: string; description?: string; created_at: string; };
export type JournalAuthor = { id: string; display_name?: string; role?: string; github_login?: string; github_profile_url?: string; avatar_url?: string; bio?: string; };
export type JournalIssue = { id: number | string; issue_number?: number; number?: number; title?: string; state?: string; issue_type?: string; html_url?: string; github_url?: string; };
export type JournalVenture = { venture_slug: string; venture_name: string; };
export type JournalTranslation = { id: string; language_code: string; translation_status: TranslationStatus; title?: string; subtitle?: string; excerpt?: string; body?: string; seo_title?: string; seo_description?: string; published_at?: string; };
export type JournalPost = { id: string; slug: string; status: JournalStatus; title: string; subtitle?: string; excerpt?: string; body?: string; content_format: ContentFormat; cover_image_url?: string; cover_image_alt?: string; original_language: string; author_profile_id?: string; category_id?: string; is_featured: boolean; is_vision_feature: boolean; published_at?: string; scheduled_for?: string; reading_time_minutes?: number; seo_title?: string; seo_description?: string; og_image_url?: string; created_at: string; updated_at: string; journal_categories?: JournalCategory | null; profiles?: JournalAuthor | null; journal_post_tags?: { journal_tags: JournalTag | null }[]; journal_post_ventures?: JournalVenture[]; journal_post_issues?: { github_issues: JournalIssue | null }[]; journal_translations?: JournalTranslation[]; };
export type PublicJournalPost = JournalPost & { displayTitle: string; displaySubtitle?: string; displayExcerpt?: string; displayBody?: string; activeLanguage: string; availableLanguages: string[] };
export type JournalIndexData = { posts: PublicJournalPost[]; categories: JournalCategory[]; tags: JournalTag[]; featured?: PublicJournalPost; visions: PublicJournalPost[]; ventureGroups: { slug: string; name: string; posts: PublicJournalPost[] }[]; };

export const JOURNAL_SELECT = '*,journal_categories(*),profiles(id,display_name,role,github_login,github_profile_url,avatar_url,bio),journal_post_tags(journal_tags(*)),journal_post_ventures(*),journal_post_issues(github_issues(id,issue_number,number,title,state,issue_type,html_url,github_url)),journal_translations(*)';
export const publicPostQuery = `select=${JOURNAL_SELECT}&status=eq.published&published_at=not.is.null&published_at=lte.${encodeURIComponent(new Date().toISOString())}&order=published_at.desc`;

async function readJson<T>(responseOrPromise: Response | Promise<Response>): Promise<T> { const response = await responseOrPromise; if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<T>; }
export function isPostPublic(post: Pick<JournalPost, 'status' | 'published_at'>, now = new Date()) { return post.status === 'published' && Boolean(post.published_at) && Date.parse(post.published_at || '') <= now.getTime(); }
export function applyTranslation(post: JournalPost, language = new URLSearchParams(location.search).get('lang') || post.original_language): PublicJournalPost { const translations = post.journal_translations || []; const published = translations.filter((t) => t.translation_status === 'published' && (!t.published_at || Date.parse(t.published_at) <= Date.now())); const t = published.find((row) => row.language_code === language); return { ...post, displayTitle: t?.title || post.title, displaySubtitle: t?.subtitle || post.subtitle, displayExcerpt: t?.excerpt || post.excerpt, displayBody: t?.body || post.body, activeLanguage: t?.language_code || post.original_language, availableLanguages: [post.original_language, ...published.map((row) => row.language_code)].filter((v, i, a) => v && a.indexOf(v) === i) }; }
export function filterPosts(posts: PublicJournalPost[], opts: { category?: string; search?: string; sort?: string }) { const q = (opts.search || '').trim().toLowerCase(); return posts.filter((p) => (!opts.category || opts.category === 'all' || p.journal_categories?.slug === opts.category) && (!q || [p.displayTitle,p.displaySubtitle,p.displayExcerpt,...(p.journal_post_tags || []).map((t)=>t.journal_tags?.name),...(p.journal_post_ventures || []).map((v)=>v.venture_name)].filter(Boolean).join(' ').toLowerCase().includes(q))).sort((a,b)=> opts.sort === 'updated' ? Date.parse(b.updated_at)-Date.parse(a.updated_at) : opts.sort === 'short' ? (a.reading_time_minutes||999)-(b.reading_time_minutes||999) : opts.sort === 'long' ? (b.reading_time_minutes||0)-(a.reading_time_minutes||0) : Date.parse(b.published_at || '')-Date.parse(a.published_at || '')); }
export function sanitizeMarkdown(markdown = '') { let html = markdown.replace(/[&<>]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!)); html = html.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^&gt; (.*)$/gm,'<blockquote>$1</blockquote>').replace(/!\[([^\]]*)\]\((https?:\/\/[^\s)]+)\)/g,'<img src="$2" alt="$1" loading="lazy" />').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1<span class="visually-hidden"> (opens in a new tab)</span></a>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n{2,}/g,'</p><p>').replace(/\n/g,'<br />'); return `<p>${html}</p>`.replace(/<p><h/g,'<h').replace(/<\/h([123])><\/p>/g,'</h$1>').replace(/<p><blockquote>/g,'<blockquote>').replace(/<\/blockquote><\/p>/g,'</blockquote>'); }
export async function getJournalIndex(): Promise<JournalIndexData> { const [posts,categories,tags] = await Promise.all([readJson<JournalPost[]>(supabase.from('journal_posts').request({ query: publicPostQuery })), readJson<JournalCategory[]>(supabase.from('journal_categories').request({ query: 'select=*&is_public=eq.true&order=display_order.asc' })), readJson<JournalTag[]>(supabase.from('journal_tags').request({ query: 'select=*&order=name.asc' }))]); const publicPosts = posts.filter((p)=>isPostPublic(p)).map((p)=>applyTranslation(p)); return { posts: publicPosts, categories, tags, featured: publicPosts.find((p)=>p.is_featured), visions: publicPosts.filter((p)=>p.is_vision_feature), ventureGroups: Object.values(publicPosts.flatMap((p)=>p.journal_post_ventures || []).reduce<Record<string,{slug:string;name:string;posts:PublicJournalPost[]}>>((acc,v)=>{ acc[v.venture_slug] ||= { slug:v.venture_slug, name:v.venture_name, posts: publicPosts.filter((p)=>p.journal_post_ventures?.some((pv)=>pv.venture_slug===v.venture_slug)) }; return acc; },{})) }; }
export async function getJournalPost(slug: string): Promise<PublicJournalPost | null> { const rows = await readJson<JournalPost[]>(supabase.from('journal_posts').request({ query: `${publicPostQuery}&slug=eq.${encodeURIComponent(slug)}` })); const post = rows.find((p)=>p.slug === slug && isPostPublic(p)); return post ? applyTranslation(post) : null; }
export async function subscribeToJournal(email: string, preferred_language: string) { const normalized = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(normalized)) throw new Error('Enter a valid email address.'); const response = await supabase.from('newsletter_subscribers').request({ method: 'POST', headers: { Prefer: 'return=representation' }, body: { email: normalized, preferred_language, status: 'active', source: 'journal', consent_at: new Date().toISOString() } }); if (response.status === 409) return { duplicate: true }; await readJson(response); return { duplicate: false }; }
export async function submitStory(input: { name: string; email: string; submission_type: string; title: string; summary: string; body: string; consent_to_contact: boolean; consent_to_publish: boolean }, session?: SupabaseSession | null) { if (!input.title.trim() || !input.summary.trim() || !input.body.trim()) throw new Error('Title, summary and story body are required.'); if (!input.consent_to_contact) throw new Error('Consent to contact is required so editors can moderate submissions.'); await readJson(supabase.from('journal_story_submissions').request({ method: 'POST', accessToken: session?.access_token, headers: { Prefer: 'return=representation' }, body: { ...input, email: input.email.trim().toLowerCase(), status: 'pending', submitted_by_profile_id: session?.user.id || null } })); }
