import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, LoaderCircle, Network, RefreshCw } from 'lucide-react';
import { getAdminAiHierarchy, type AdminAiHierarchyRow } from '../lib/adminAiHierarchyApi';
import type { I18nManifest } from '../lib/i18nManifest';
import { useWebsiteI18n } from '../lib/websiteI18n';

export const ADMIN_AI_HIERARCHY_PAGE_I18N_MANIFEST = {
  componentKey: 'admin.ai_hierarchy.page', namespace: 'admin.ai_hierarchy',
  translationKeys: ['admin.ai_hierarchy.eyebrow','admin.ai_hierarchy.title','admin.ai_hierarchy.description','admin.ai_hierarchy.loading','admin.ai_hierarchy.error','admin.ai_hierarchy.empty','admin.ai_hierarchy.refresh','admin.ai_hierarchy.graph_label','admin.ai_hierarchy.diagnostics','admin.ai_hierarchy.cycles','admin.ai_hierarchy.orphans','admin.ai_hierarchy.team'] as const,
  entityContent: { rpc: 'admin_get_ai_hierarchy', tables: ['ai_agents', 'ai_teams'] },
} as const satisfies I18nManifest;

type MermaidApi = { initialize: (options: Record<string, unknown>) => void; render: (id: string, definition: string) => Promise<{ svg: string }> };
declare global { interface Window { mermaid?: MermaidApi } }
function nodeId(id: string) { return `agent_${id.replaceAll('-', '_')}`; }
function label(value: string) { return value.replaceAll('"', "'").replaceAll('[', '(').replaceAll(']', ')').replaceAll('\n', ' '); }
function analyse(rows: AdminAiHierarchyRow[]) {
  const ids = new Set(rows.map((row) => row.agent_id)); const orphans = rows.filter((row) => row.reports_to_agent_id && !ids.has(row.reports_to_agent_id)); const cycles: string[][] = []; const seen = new Set<string>();
  for (const row of rows) { const path: string[] = []; const positions = new Map<string, number>(); let current: string | null = row.agent_id; while (current) { if (positions.has(current)) { const cycle = path.slice(positions.get(current)); const key = [...cycle].sort().join('|'); if (!seen.has(key)) { seen.add(key); cycles.push(cycle); } break; } positions.set(current, path.length); path.push(current); current = rows.find((candidate) => candidate.agent_id === current)?.reports_to_agent_id || null; if (current && !ids.has(current)) break; } }
  return { orphans, cycles };
}
function graphDefinition(rows: AdminAiHierarchyRow[]) { const lines = ['flowchart TD']; for (const row of rows) lines.push(`  ${nodeId(row.agent_id)}["${label(row.agent_name)}<br/><small>${label(row.agent_title)}</small>"]`); for (const row of rows) if (row.reports_to_agent_id && rows.some((candidate) => candidate.agent_id === row.reports_to_agent_id)) lines.push(`  ${nodeId(row.reports_to_agent_id)} --> ${nodeId(row.agent_id)}`); return lines.join('\n'); }
async function loadMermaid(): Promise<MermaidApi> { if (window.mermaid) return window.mermaid; await new Promise<void>((resolve, reject) => { const existing = document.querySelector<HTMLScriptElement>('script[data-admin-mermaid]'); if (existing) { existing.addEventListener('load', () => resolve(), { once: true }); existing.addEventListener('error', () => reject(new Error('Mermaid library could not be loaded.')), { once: true }); return; } const script = document.createElement('script'); script.dataset.adminMermaid = 'true'; script.src = 'https://cdn.jsdelivr.net/npm/mermaid@11.16.0/dist/mermaid.min.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('Mermaid library could not be loaded.')); document.head.appendChild(script); }); if (!window.mermaid) throw new Error('Mermaid library is unavailable.'); return window.mermaid; }

export function AdminAiHierarchyPage() {
  const { t } = useWebsiteI18n(); const [rows, setRows] = useState<AdminAiHierarchyRow[] | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const graphRef = useRef<HTMLDivElement>(null); const diagnostics = useMemo(() => (rows ? analyse(rows) : null), [rows]);
  const load = async () => { setLoading(true); setError(null); try { setRows(await getAdminAiHierarchy()); } catch (reason) { setRows(null); setError(reason instanceof Error ? reason.message : t('admin.ai_hierarchy.error', 'The AI hierarchy could not be loaded.')); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [t]);
  useEffect(() => { if (!rows?.length || !graphRef.current) return; let cancelled = false; void loadMermaid().then((mermaid) => { mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme: 'dark' }); return mermaid.render('admin-ai-hierarchy-graph', graphDefinition(rows)); }).then(({ svg }) => { if (!cancelled && graphRef.current) graphRef.current.innerHTML = svg; }).catch((reason) => { if (!cancelled) setError(reason instanceof Error ? reason.message : 'Mermaid render failed.'); }); return () => { cancelled = true; }; }, [rows]);
  return <section className="admin-ai-hierarchy" aria-labelledby="admin-ai-hierarchy-title"><header className="admin-section-heading"><div><p>{t('admin.ai_hierarchy.eyebrow', 'AI GOVERNANCE')}</p><h1 id="admin-ai-hierarchy-title">{t('admin.ai_hierarchy.title', 'Live AI hierarchy')}</h1><span>{t('admin.ai_hierarchy.description', 'Read-only view of agents, teams and reporting relationships from Supabase.')}</span></div><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw size={16} />{t('admin.ai_hierarchy.refresh', 'Refresh')}</button></header>{loading && <div className="admin-loading"><LoaderCircle className="spin" />{t('admin.ai_hierarchy.loading', 'Loading the live AI hierarchy…')}</div>}{error && <div className="admin-error" role="alert"><AlertTriangle size={18} /><span>{error}</span></div>}{!loading && !error && rows && rows.length === 0 && <div className="admin-empty">{t('admin.ai_hierarchy.empty', 'No AI agents are available.')}</div>}{!loading && !error && rows && rows.length > 0 && <><div className="admin-ai-hierarchy__meta"><Network size={17} /><span>{rows.length} agents · {new Set(rows.map((row) => row.team_id)).size} teams</span></div>{diagnostics && (diagnostics.cycles.length > 0 || diagnostics.orphans.length > 0) && <aside className="admin-ai-hierarchy__diagnostics" aria-label={t('admin.ai_hierarchy.diagnostics', 'Hierarchy diagnostics')}><strong>{t('admin.ai_hierarchy.diagnostics', 'Hierarchy diagnostics')}</strong>{diagnostics.cycles.length > 0 && <span>{t('admin.ai_hierarchy.cycles', 'Cycles detected')}: {diagnostics.cycles.length}</span>}{diagnostics.orphans.length > 0 && <span>{t('admin.ai_hierarchy.orphans', 'Orphaned agents')}: {diagnostics.orphans.length}</span>}</aside>}<div className="admin-panel admin-ai-hierarchy__graph" ref={graphRef} role="img" aria-label={t('admin.ai_hierarchy.graph_label', 'Mermaid diagram of the live AI hierarchy')} /></>}</section>;
}
