insert into public.website_translation_keys
  (translation_key, namespace, description, default_text, value_type, is_required, is_active, interpolation_variables, supports_plural)
values
  ('journal.map.empty.title', 'journal', 'Empty state title when no mapped journey chapters exist', 'The first mapped chapter is coming.', 'text', true, true, '{}', false),
  ('journal.map.empty.body', 'journal', 'Empty state body when no mapped journey chapters exist', 'Publish a journey location with coordinates to activate the route.', 'text', true, true, '{}', false),
  ('journal.map.kpi.mapped_chapters', 'journal', 'KPI label for mapped chapter count', 'mapped chapters', 'text', true, true, '{}', false),
  ('journal.map.kpi.road_distance', 'journal', 'KPI label when routed road distance is available', 'road distance', 'text', true, true, '{}', false),
  ('journal.map.kpi.route_position', 'journal', 'KPI label when route position is shown instead of distance', 'route position', 'text', true, true, '{}', false),
  ('journal.map.kpi.current_stop', 'journal', 'KPI label for the current journey stop', 'current stop', 'text', true, true, '{}', false),
  ('journal.map.kpi.open_road', 'journal', 'Fallback label when no current stop location name exists', 'Open road', 'text', true, true, '{}', false),
  ('journal.map.badge.live_map', 'journal', 'Badge label for the live journey map card', 'Live journey map', 'text', true, true, '{}', false),
  ('journal.map.topbar.subtitle', 'journal', 'Subtitle under the live journey map badge', 'Separate road routes for Kevin and Micha · database-linked profile pins', 'text', true, true, '{}', false),
  ('journal.map.action.current', 'journal', 'Button label to focus the map on the current stop', 'Current', 'text', true, true, '{}', false),
  ('journal.map.action.fullscreen', 'journal', 'Button label to open the map in fullscreen', 'Fullscreen', 'text', true, true, '{}', false),
  ('journal.map.error.load_failed', 'journal', 'Error shown when the interactive map fails to load', 'The interactive map could not load. Check the connection and refresh.', 'text', true, true, '{}', false),
  ('journal.map.error.routing_fallback', 'journal', 'Notice shown when road routing is unavailable', 'Road routing is temporarily unavailable; simplified lines are shown.', 'text', true, true, '{}', false),
  ('journal.map.floating.journey_view', 'journal', 'Floating label on the journey map canvas', 'Journey view', 'text', true, true, '{}', false),
  ('journal.map.legend.kevin_route', 'journal', 'Legend label for Kevin route line', 'Kevin route', 'text', true, true, '{}', false),
  ('journal.map.legend.micha_route', 'journal', 'Legend label for Micha route line', 'Micha route', 'text', true, true, '{}', false),
  ('journal.map.legend.shared_stop', 'journal', 'Legend label for shared journey stops', 'Shared stop', 'text', true, true, '{}', false),
  ('journal.map.detail.live_location', 'journal', 'Badge label for the live location chapter', 'Live location', 'text', true, true, '{}', false),
  ('journal.map.detail.journey_progress', 'journal', 'Progress label in the map detail card', 'Journey progress', 'text', true, true, '{}', false),
  ('journal.map.detail.read_chapter', 'journal', 'Link label to open the selected journal chapter', 'Read this chapter', 'text', true, true, '{}', false),
  ('journal.map.nav.previous', 'journal', 'Previous chapter button on the map detail card', 'Previous', 'text', true, true, '{}', false),
  ('journal.map.nav.next', 'journal', 'Next chapter button on the map detail card', 'Next', 'text', true, true, '{}', false)
on conflict (translation_key) do update
set default_text = excluded.default_text,
    description = excluded.description,
    is_active = true,
    updated_at = now();

with catalog(translation_key, language_code, translated_text) as (
  values
    ('journal.map.empty.title','en','The first mapped chapter is coming.'),('journal.map.empty.title','nl','Het eerste kaart-hoofdstuk komt eraan.'),('journal.map.empty.title','fr','Le premier chapitre cartographié arrive.'),('journal.map.empty.title','de','Das erste kartierte Kapitel kommt.'),('journal.map.empty.title','es','El primer capítulo cartografiado está en camino.'),('journal.map.empty.title','pt','O primeiro capítulo mapeado está a caminho.'),('journal.map.empty.title','it','Il primo capitolo mappato sta arrivando.'),('journal.map.empty.title','pl','Pierwszy rozdział na mapie już wkrótce.'),('journal.map.empty.title','cs','První zmapovaná kapitola se blíží.'),('journal.map.empty.title','tr','Haritalanan ilk bölüm yolda.'),('journal.map.empty.title','ar','الفصل الأول على الخريطة قادم.'),('journal.map.empty.title','hi','पहला मैप किया गया अध्याय आ रहा है।'),('journal.map.empty.title','zh','第一个地图章节即将上线。'),('journal.map.empty.title','ja','最初のマップ章が間もなく公開されます。'),('journal.map.empty.title','ko','첫 번째 지도 챕터가 곧 공개됩니다.'),
    ('journal.map.empty.body','en','Publish a journey location with coordinates to activate the route.'),('journal.map.empty.body','nl','Publiceer een reislocatie met coördinaten om de route te activeren.'),('journal.map.empty.body','fr','Publiez un lieu de voyage avec des coordonnées pour activer l’itinéraire.'),('journal.map.empty.body','de','Veröffentliche einen Reiseort mit Koordinaten, um die Route zu aktivieren.'),('journal.map.empty.body','es','Publica una ubicación del viaje con coordenadas para activar la ruta.'),('journal.map.empty.body','pt','Publique um local da jornada com coordenadas para ativar a rota.'),('journal.map.empty.body','it','Pubblica una tappa del viaggio con coordinate per attivare il percorso.'),('journal.map.empty.body','pl','Opublikuj lokalizację podróży ze współrzędnymi, aby aktywować trasę.'),('journal.map.empty.body','cs','Publikujte místo cesty se souřadnicemi, aby se aktivovala trasa.'),('journal.map.empty.body','tr','Rotayı etkinleştirmek için koordinatlı bir yolculuk konumu yayınlayın.'),('journal.map.empty.body','ar','انشر موقعًا للرحلة بإحداثيات لتفعيل المسار.'),('journal.map.empty.body','hi','मार्ग सक्रिय करने के लिए निर्देशांक के साथ यात्रा स्थान प्रकाशित करें।'),('journal.map.empty.body','zh','发布带坐标的旅程地点以激活路线。'),('journal.map.empty.body','ja','ルートを有効にするには、座標付きの旅地点を公開してください。'),('journal.map.empty.body','ko','경로를 활성화하려면 좌표가 있는 여정 위치를 게시하세요.'),
    ('journal.map.kpi.mapped_chapters','en','mapped chapters'),('journal.map.kpi.mapped_chapters','nl','kaart-hoofdstukken'),('journal.map.kpi.mapped_chapters','fr','chapitres cartographiés'),('journal.map.kpi.mapped_chapters','de','kartierte Kapitel'),('journal.map.kpi.mapped_chapters','es','capítulos cartografiados'),('journal.map.kpi.mapped_chapters','pt','capítulos mapeados'),('journal.map.kpi.mapped_chapters','it','capitoli mappati'),('journal.map.kpi.mapped_chapters','pl','rozdziały na mapie'),('journal.map.kpi.mapped_chapters','cs','zmapované kapitoly'),('journal.map.kpi.mapped_chapters','tr','haritalanan bölümler'),('journal.map.kpi.mapped_chapters','ar','فصول على الخريطة'),('journal.map.kpi.mapped_chapters','hi','मैप किए गए अध्याय'),('journal.map.kpi.mapped_chapters','zh','已映射章节'),('journal.map.kpi.mapped_chapters','ja','マップ章'),('journal.map.kpi.mapped_chapters','ko','지도 챕터'),
    ('journal.map.kpi.road_distance','en','road distance'),('journal.map.kpi.road_distance','nl','wegafstand'),('journal.map.kpi.road_distance','fr','distance routière'),('journal.map.kpi.road_distance','de','Straßendistanz'),('journal.map.kpi.road_distance','es','distancia por carretera'),('journal.map.kpi.road_distance','pt','distância rodoviária'),('journal.map.kpi.road_distance','it','distanza su strada'),('journal.map.kpi.road_distance','pl','dystans drogowy'),('journal.map.kpi.road_distance','cs','silniční vzdálenost'),('journal.map.kpi.road_distance','tr','karayolu mesafesi'),('journal.map.kpi.road_distance','ar','مسافة الطريق'),('journal.map.kpi.road_distance','hi','सड़क दूरी'),('journal.map.kpi.road_distance','zh','道路距离'),('journal.map.kpi.road_distance','ja','道路距離'),('journal.map.kpi.road_distance','ko','도로 거리'),
    ('journal.map.kpi.route_position','en','route position'),('journal.map.kpi.route_position','nl','routepositie'),('journal.map.kpi.route_position','fr','position sur l’itinéraire'),('journal.map.kpi.route_position','de','Routenposition'),('journal.map.kpi.route_position','es','posición en la ruta'),('journal.map.kpi.route_position','pt','posição na rota'),('journal.map.kpi.route_position','it','posizione sul percorso'),('journal.map.kpi.route_position','pl','pozycja na trasie'),('journal.map.kpi.route_position','cs','pozice na trase'),('journal.map.kpi.route_position','tr','rota konumu'),('journal.map.kpi.route_position','ar','موضع المسار'),('journal.map.kpi.route_position','hi','मार्ग स्थिति'),('journal.map.kpi.route_position','zh','路线位置'),('journal.map.kpi.route_position','ja','ルート位置'),('journal.map.kpi.route_position','ko','경로 위치'),
    ('journal.map.kpi.current_stop','en','current stop'),('journal.map.kpi.current_stop','nl','huidige stop'),('journal.map.kpi.current_stop','fr','étape actuelle'),('journal.map.kpi.current_stop','de','aktueller Stopp'),('journal.map.kpi.current_stop','es','parada actual'),('journal.map.kpi.current_stop','pt','parada atual'),('journal.map.kpi.current_stop','it','tappa attuale'),('journal.map.kpi.current_stop','pl','obecny przystanek'),('journal.map.kpi.current_stop','cs','aktuální zastávka'),('journal.map.kpi.current_stop','tr','mevcut durak'),('journal.map.kpi.current_stop','ar','المحطة الحالية'),('journal.map.kpi.current_stop','hi','वर्तमान पड़ाव'),('journal.map.kpi.current_stop','zh','当前站点'),('journal.map.kpi.current_stop','ja','現在の停留地'),('journal.map.kpi.current_stop','ko','현재 정거장'),
    ('journal.map.kpi.open_road','en','Open road'),('journal.map.kpi.open_road','nl','Open weg'),('journal.map.kpi.open_road','fr','Route ouverte'),('journal.map.kpi.open_road','de','Offene Straße'),('journal.map.kpi.open_road','es','Carretera abierta'),('journal.map.kpi.open_road','pt','Estrada aberta'),('journal.map.kpi.open_road','it','Strada aperta'),('journal.map.kpi.open_road','pl','Otwarta droga'),('journal.map.kpi.open_road','cs','Otevřená cesta'),('journal.map.kpi.open_road','tr','Açık yol'),('journal.map.kpi.open_road','ar','طريق مفتوح'),('journal.map.kpi.open_road','hi','खुली सड़क'),('journal.map.kpi.open_road','zh','开放道路'),('journal.map.kpi.open_road','ja','オープンロード'),('journal.map.kpi.open_road','ko','열린 길'),
    ('journal.map.badge.live_map','en','Live journey map'),('journal.map.badge.live_map','nl','Live reiskaart'),('journal.map.badge.live_map','fr','Carte du voyage en direct'),('journal.map.badge.live_map','de','Live-Reisekarte'),('journal.map.badge.live_map','es','Mapa del viaje en vivo'),('journal.map.badge.live_map','pt','Mapa da jornada ao vivo'),('journal.map.badge.live_map','it','Mappa del viaggio live'),('journal.map.badge.live_map','pl','Mapa podróży na żywo'),('journal.map.badge.live_map','cs','Živá mapa cesty'),('journal.map.badge.live_map','tr','Canlı yolculuk haritası'),('journal.map.badge.live_map','ar','خريطة الرحلة المباشرة'),('journal.map.badge.live_map','hi','लाइव यात्रा मानचित्र'),('journal.map.badge.live_map','zh','实时旅程地图'),('journal.map.badge.live_map','ja','ライブ旅マップ'),('journal.map.badge.live_map','ko','실시간 여정 지도'),
    ('journal.map.topbar.subtitle','en','Separate road routes for Kevin and Micha · database-linked profile pins'),('journal.map.topbar.subtitle','nl','Aparte wegroutes voor Kevin en Micha · databank-gekoppelde profielpinnen'),('journal.map.topbar.subtitle','fr','Itinéraires routiers séparés pour Kevin et Micha · repères de profil liés à la base de données'),('journal.map.topbar.subtitle','de','Getrennte Straßenrouten für Kevin und Micha · datenbankverknüpfte Profil-Pins'),('journal.map.topbar.subtitle','es','Rutas por carretera separadas para Kevin y Micha · pins de perfil vinculados a la base de datos'),('journal.map.topbar.subtitle','pt','Rotas rodoviárias separadas para Kevin e Micha · pins de perfil ligados à base de dados'),('journal.map.topbar.subtitle','it','Percorsi stradali separati per Kevin e Micha · pin profilo collegati al database'),('journal.map.topbar.subtitle','pl','Oddzielne trasy drogowe dla Kevin i Micha · pinezki profili powiązane z bazą danych'),('journal.map.topbar.subtitle','cs','Samostatné silniční trasy pro Kevin a Micha · profilové piny napojené na databázi'),('journal.map.topbar.subtitle','tr','Kevin ve Micha için ayrı karayolu rotaları · veritabanına bağlı profil pinleri'),('journal.map.topbar.subtitle','ar','مسارات طرق منفصلة لـ Kevin وMicha · دبابيس ملفات مرتبطة بقاعدة البيانات'),('journal.map.topbar.subtitle','hi','Kevin और Micha के लिए अलग सड़क मार्ग · डेटाबेस-लिंक्ड प्रोफ़ाइल पिन'),('journal.map.topbar.subtitle','zh','Kevin 和 Micha 的独立公路路线 · 数据库关联的个人资料标记'),('journal.map.topbar.subtitle','ja','KevinとMichaの個別道路ルート · データベース連携プロフィールピン'),('journal.map.topbar.subtitle','ko','Kevin과 Micha의 별도 도로 경로 · 데이터베이스 연결 프로필 핀'),
    ('journal.map.action.current','en','Current'),('journal.map.action.current','nl','Huidig'),('journal.map.action.current','fr','Actuel'),('journal.map.action.current','de','Aktuell'),('journal.map.action.current','es','Actual'),('journal.map.action.current','pt','Atual'),('journal.map.action.current','it','Attuale'),('journal.map.action.current','pl','Bieżący'),('journal.map.action.current','cs','Aktuální'),('journal.map.action.current','tr','Güncel'),('journal.map.action.current','ar','الحالي'),('journal.map.action.current','hi','वर्तमान'),('journal.map.action.current','zh','当前'),('journal.map.action.current','ja','現在'),('journal.map.action.current','ko','현재'),
    ('journal.map.action.fullscreen','en','Fullscreen'),('journal.map.action.fullscreen','nl','Volledig scherm'),('journal.map.action.fullscreen','fr','Plein écran'),('journal.map.action.fullscreen','de','Vollbild'),('journal.map.action.fullscreen','es','Pantalla completa'),('journal.map.action.fullscreen','pt','Ecrã inteiro'),('journal.map.action.fullscreen','it','Schermo intero'),('journal.map.action.fullscreen','pl','Pełny ekran'),('journal.map.action.fullscreen','cs','Celá obrazovka'),('journal.map.action.fullscreen','tr','Tam ekran'),('journal.map.action.fullscreen','ar','ملء الشاشة'),('journal.map.action.fullscreen','hi','पूर्ण स्क्रीन'),('journal.map.action.fullscreen','zh','全屏'),('journal.map.action.fullscreen','ja','全画面'),('journal.map.action.fullscreen','ko','전체 화면'),
    ('journal.map.error.load_failed','en','The interactive map could not load. Check the connection and refresh.'),('journal.map.error.load_failed','nl','De interactieve kaart kon niet laden. Controleer de verbinding en ververs de pagina.'),('journal.map.error.load_failed','fr','La carte interactive n’a pas pu se charger. Vérifiez la connexion et actualisez.'),('journal.map.error.load_failed','de','Die interaktive Karte konnte nicht geladen werden. Verbindung prüfen und Seite aktualisieren.'),('journal.map.error.load_failed','es','No se pudo cargar el mapa interactivo. Comprueba la conexión y actualiza.'),('journal.map.error.load_failed','pt','Não foi possível carregar o mapa interativo. Verifique a ligação e atualize.'),('journal.map.error.load_failed','it','Impossibile caricare la mappa interattiva. Controlla la connessione e aggiorna.'),('journal.map.error.load_failed','pl','Nie udało się wczytać interaktywnej mapy. Sprawdź połączenie i odśwież stronę.'),('journal.map.error.load_failed','cs','Interaktivní mapu se nepodařilo načíst. Zkontrolujte připojení a obnovte stránku.'),('journal.map.error.load_failed','tr','Etkileşimli harita yüklenemedi. Bağlantıyı kontrol edin ve yenileyin.'),('journal.map.error.load_failed','ar','تعذر تحميل الخريطة التفاعلية. تحقق من الاتصال ثم حدّث الصفحة.'),('journal.map.error.load_failed','hi','इंटरैक्टिव मानचित्र लोड नहीं हो सका। कनेक्शन जांचें और रीफ़्रेश करें।'),('journal.map.error.load_failed','zh','无法加载交互式地图。请检查连接并刷新。'),('journal.map.error.load_failed','ja','インタラクティブマップを読み込めませんでした。接続を確認して更新してください。'),('journal.map.error.load_failed','ko','인터랙티브 지도를 불러오지 못했습니다. 연결을 확인한 뒤 새로고침하세요.'),
    ('journal.map.error.routing_fallback','en','Road routing is temporarily unavailable; simplified lines are shown.'),('journal.map.error.routing_fallback','nl','Wegroutering is tijdelijk niet beschikbaar; vereenvoudigde lijnen worden getoond.'),('journal.map.error.routing_fallback','fr','Le routage routier est temporairement indisponible ; des lignes simplifiées sont affichées.'),('journal.map.error.routing_fallback','de','Straßenrouting ist vorübergehend nicht verfügbar; vereinfachte Linien werden angezeigt.'),('journal.map.error.routing_fallback','es','El enrutamiento por carretera no está disponible temporalmente; se muestran líneas simplificadas.'),('journal.map.error.routing_fallback','pt','O encaminhamento rodoviário está temporariamente indisponível; são mostradas linhas simplificadas.'),('journal.map.error.routing_fallback','it','Il routing stradale è temporaneamente non disponibile; vengono mostrate linee semplificate.'),('journal.map.error.routing_fallback','pl','Routing drogowy jest tymczasowo niedostępny; pokazano uproszczone linie.'),('journal.map.error.routing_fallback','cs','Silniční routing je dočasně nedostupný; zobrazují se zjednodušené linie.'),('journal.map.error.routing_fallback','tr','Karayolu yönlendirmesi geçici olarak kullanılamıyor; basitleştirilmiş çizgiler gösteriliyor.'),('journal.map.error.routing_fallback','ar','توجيه الطرق غير متاح مؤقتًا؛ يتم عرض خطوط مبسطة.'),('journal.map.error.routing_fallback','hi','सड़क रूटिंग अस्थायी रूप से उपलब्ध नहीं है; सरलीकृत रेखाएँ दिखाई जा रही हैं।'),('journal.map.error.routing_fallback','zh','道路路线规划暂时不可用；显示简化线条。'),('journal.map.error.routing_fallback','ja','道路ルーティングは一時的に利用できません。簡略化された線が表示されています。'),('journal.map.error.routing_fallback','ko','도로 경로 안내를 일시적으로 사용할 수 없습니다. 단순화된 선이 표시됩니다.'),
    ('journal.map.floating.journey_view','en','Journey view'),('journal.map.floating.journey_view','nl','Reisweergave'),('journal.map.floating.journey_view','fr','Vue du voyage'),('journal.map.floating.journey_view','de','Reiseansicht'),('journal.map.floating.journey_view','es','Vista del viaje'),('journal.map.floating.journey_view','pt','Vista da jornada'),('journal.map.floating.journey_view','it','Vista del viaggio'),('journal.map.floating.journey_view','pl','Widok podróży'),('journal.map.floating.journey_view','cs','Pohled na cestu'),('journal.map.floating.journey_view','tr','Yolculuk görünümü'),('journal.map.floating.journey_view','ar','عرض الرحلة'),('journal.map.floating.journey_view','hi','यात्रा दृश्य'),('journal.map.floating.journey_view','zh','旅程视图'),('journal.map.floating.journey_view','ja','旅ビュー'),('journal.map.floating.journey_view','ko','여정 보기'),
    ('journal.map.legend.kevin_route','en','Kevin route'),('journal.map.legend.kevin_route','nl','Kevin-route'),('journal.map.legend.kevin_route','fr','Itinéraire de Kevin'),('journal.map.legend.kevin_route','de','Kevin-Route'),('journal.map.legend.kevin_route','es','Ruta de Kevin'),('journal.map.legend.kevin_route','pt','Rota de Kevin'),('journal.map.legend.kevin_route','it','Percorso di Kevin'),('journal.map.legend.kevin_route','pl','Trasa Kevin'),('journal.map.legend.kevin_route','cs','Kevinova trasa'),('journal.map.legend.kevin_route','tr','Kevin rotası'),('journal.map.legend.kevin_route','ar','مسار Kevin'),('journal.map.legend.kevin_route','hi','Kevin मार्ग'),('journal.map.legend.kevin_route','zh','Kevin 路线'),('journal.map.legend.kevin_route','ja','Kevinルート'),('journal.map.legend.kevin_route','ko','Kevin 경로'),
    ('journal.map.legend.micha_route','en','Micha route'),('journal.map.legend.micha_route','nl','Micha-route'),('journal.map.legend.micha_route','fr','Itinéraire de Micha'),('journal.map.legend.micha_route','de','Micha-Route'),('journal.map.legend.micha_route','es','Ruta de Micha'),('journal.map.legend.micha_route','pt','Rota de Micha'),('journal.map.legend.micha_route','it','Percorso di Micha'),('journal.map.legend.micha_route','pl','Trasa Micha'),('journal.map.legend.micha_route','cs','Michova trasa'),('journal.map.legend.micha_route','tr','Micha rotası'),('journal.map.legend.micha_route','ar','مسار Micha'),('journal.map.legend.micha_route','hi','Micha मार्ग'),('journal.map.legend.micha_route','zh','Micha 路线'),('journal.map.legend.micha_route','ja','Michaルート'),('journal.map.legend.micha_route','ko','Micha 경로'),
    ('journal.map.legend.shared_stop','en','Shared stop'),('journal.map.legend.shared_stop','nl','Gedeelde stop'),('journal.map.legend.shared_stop','fr','Étape partagée'),('journal.map.legend.shared_stop','de','Gemeinsamer Stopp'),('journal.map.legend.shared_stop','es','Parada compartida'),('journal.map.legend.shared_stop','pt','Parada partilhada'),('journal.map.legend.shared_stop','it','Tappa condivisa'),('journal.map.legend.shared_stop','pl','Wspólny przystanek'),('journal.map.legend.shared_stop','cs','Sdílená zastávka'),('journal.map.legend.shared_stop','tr','Ortak durak'),('journal.map.legend.shared_stop','ar','محطة مشتركة'),('journal.map.legend.shared_stop','hi','साझा पड़ाव'),('journal.map.legend.shared_stop','zh','共享站点'),('journal.map.legend.shared_stop','ja','共有停留地'),('journal.map.legend.shared_stop','ko','공유 정거장'),
    ('journal.map.detail.live_location','en','Live location'),('journal.map.detail.live_location','nl','Live locatie'),('journal.map.detail.live_location','fr','Localisation en direct'),('journal.map.detail.live_location','de','Live-Standort'),('journal.map.detail.live_location','es','Ubicación en vivo'),('journal.map.detail.live_location','pt','Localização ao vivo'),('journal.map.detail.live_location','it','Posizione live'),('journal.map.detail.live_location','pl','Lokalizacja na żywo'),('journal.map.detail.live_location','cs','Aktuální poloha'),('journal.map.detail.live_location','tr','Canlı konum'),('journal.map.detail.live_location','ar','الموقع المباشر'),('journal.map.detail.live_location','hi','लाइव स्थान'),('journal.map.detail.live_location','zh','实时位置'),('journal.map.detail.live_location','ja','ライブ位置'),('journal.map.detail.live_location','ko','실시간 위치'),
    ('journal.map.detail.journey_progress','en','Journey progress'),('journal.map.detail.journey_progress','nl','Reisvoortgang'),('journal.map.detail.journey_progress','fr','Progression du voyage'),('journal.map.detail.journey_progress','de','Reisefortschritt'),('journal.map.detail.journey_progress','es','Progreso del viaje'),('journal.map.detail.journey_progress','pt','Progresso da jornada'),('journal.map.detail.journey_progress','it','Progresso del viaggio'),('journal.map.detail.journey_progress','pl','Postęp podróży'),('journal.map.detail.journey_progress','cs','Postup cesty'),('journal.map.detail.journey_progress','tr','Yolculuk ilerlemesi'),('journal.map.detail.journey_progress','ar','تقدم الرحلة'),('journal.map.detail.journey_progress','hi','यात्रा प्रगति'),('journal.map.detail.journey_progress','zh','旅程进度'),('journal.map.detail.journey_progress','ja','旅の進捗'),('journal.map.detail.journey_progress','ko','여정 진행률'),
    ('journal.map.detail.read_chapter','en','Read this chapter'),('journal.map.detail.read_chapter','nl','Lees dit hoofdstuk'),('journal.map.detail.read_chapter','fr','Lire ce chapitre'),('journal.map.detail.read_chapter','de','Dieses Kapitel lesen'),('journal.map.detail.read_chapter','es','Leer este capítulo'),('journal.map.detail.read_chapter','pt','Ler este capítulo'),('journal.map.detail.read_chapter','it','Leggi questo capitolo'),('journal.map.detail.read_chapter','pl','Przeczytaj ten rozdział'),('journal.map.detail.read_chapter','cs','Přečíst tuto kapitolu'),('journal.map.detail.read_chapter','tr','Bu bölümü oku'),('journal.map.detail.read_chapter','ar','اقرأ هذا الفصل'),('journal.map.detail.read_chapter','hi','यह अध्याय पढ़ें'),('journal.map.detail.read_chapter','zh','阅读此章节'),('journal.map.detail.read_chapter','ja','この章を読む'),('journal.map.detail.read_chapter','ko','이 챕터 읽기'),
    ('journal.map.nav.previous','en','Previous'),('journal.map.nav.previous','nl','Vorige'),('journal.map.nav.previous','fr','Précédent'),('journal.map.nav.previous','de','Zurück'),('journal.map.nav.previous','es','Anterior'),('journal.map.nav.previous','pt','Anterior'),('journal.map.nav.previous','it','Precedente'),('journal.map.nav.previous','pl','Poprzedni'),('journal.map.nav.previous','cs','Předchozí'),('journal.map.nav.previous','tr','Önceki'),('journal.map.nav.previous','ar','السابق'),('journal.map.nav.previous','hi','पिछला'),('journal.map.nav.previous','zh','上一章'),('journal.map.nav.previous','ja','前へ'),('journal.map.nav.previous','ko','이전'),
    ('journal.map.nav.next','en','Next'),('journal.map.nav.next','nl','Volgende'),('journal.map.nav.next','fr','Suivant'),('journal.map.nav.next','de','Weiter'),('journal.map.nav.next','es','Siguiente'),('journal.map.nav.next','pt','Seguinte'),('journal.map.nav.next','it','Successivo'),('journal.map.nav.next','pl','Następny'),('journal.map.nav.next','cs','Další'),('journal.map.nav.next','tr','Sonraki'),('journal.map.nav.next','ar','التالي'),('journal.map.nav.next','hi','अगला'),('journal.map.nav.next','zh','下一章'),('journal.map.nav.next','ja','次へ'),('journal.map.nav.next','ko','다음')
), resolved as (
  select k.id as translation_key_id, c.language_code, c.translated_text
  from catalog c
  join public.website_translation_keys k on k.translation_key = c.translation_key
)
insert into public.website_translations
  (translation_key_id, language_code, translated_text, translation_status, translation_source, translated_at, reviewed_at, published_at)
select translation_key_id, language_code, translated_text, 'published', 'manual', now(), now(), now()
from resolved
on conflict (translation_key_id, language_code) do update
set translated_text = excluded.translated_text,
    translation_status = 'published',
    translation_source = 'manual',
    translated_at = now(),
    reviewed_at = now(),
    published_at = now(),
    updated_at = now();
