create table if not exists public.journal_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, display_order integer not null default 0, is_public boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.journal_posts (id uuid primary key default gen_random_uuid(), slug text not null unique, status text not null default 'draft' check (status in ('draft','scheduled','published','archived')), title text not null, subtitle text, excerpt text, body text, content_format text not null default 'markdown' check (content_format in ('markdown','rich_text','video','mixed')), cover_image_url text, cover_image_alt text, original_language text not null default 'en', author_profile_id uuid references public.profiles(id) on delete set null, category_id uuid references public.journal_categories(id) on delete set null, is_featured boolean not null default false, is_vision_feature boolean not null default false, published_at timestamptz, scheduled_for timestamptz, reading_time_minutes integer, seo_title text, seo_description text, og_image_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.journal_tags (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, created_at timestamptz not null default now());
create table if not exists public.journal_post_tags (journal_post_id uuid not null references public.journal_posts(id) on delete cascade, tag_id uuid not null references public.journal_tags(id) on delete cascade, primary key (journal_post_id, tag_id));
create table if not exists public.journal_post_authors (journal_post_id uuid not null references public.journal_posts(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, author_order integer not null default 0, role text not null default 'author', primary key (journal_post_id, profile_id));
create table if not exists public.journal_post_ventures (journal_post_id uuid not null references public.journal_posts(id) on delete cascade, venture_slug text not null, venture_name text not null, primary key (journal_post_id, venture_slug));
create table if not exists public.journal_post_issues (journal_post_id uuid not null references public.journal_posts(id) on delete cascade, github_issue_id bigint not null references public.github_issues(id) on delete cascade, primary key (journal_post_id, github_issue_id));
create table if not exists public.journal_translations (id uuid primary key default gen_random_uuid(), journal_post_id uuid not null references public.journal_posts(id) on delete cascade, language_code text not null, translation_status text not null default 'draft' check (translation_status in ('draft','review','published','archived')), title text, subtitle text, excerpt text, body text, seo_title text, seo_description text, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (journal_post_id, language_code));
create table if not exists public.journal_story_submissions (id uuid primary key default gen_random_uuid(), submitted_by_profile_id uuid references public.profiles(id) on delete set null, name text not null, email text not null, submission_type text not null, title text not null, summary text not null, body text not null, status text not null default 'pending' check (status in ('pending','in_review','accepted','rejected','published')), consent_to_contact boolean not null default false, consent_to_publish boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.newsletter_subscribers (id uuid primary key default gen_random_uuid(), email text not null, preferred_language text not null default 'en', status text not null default 'active' check (status in ('active','unsubscribed','bounced')), source text not null default 'journal', consent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists one_active_newsletter_subscription_per_email on public.newsletter_subscribers (lower(email)) where status='active';

alter table public.journal_categories enable row level security; alter table public.journal_posts enable row level security; alter table public.journal_tags enable row level security; alter table public.journal_post_tags enable row level security; alter table public.journal_post_authors enable row level security; alter table public.journal_post_ventures enable row level security; alter table public.journal_post_issues enable row level security; alter table public.journal_translations enable row level security; alter table public.journal_story_submissions enable row level security; alter table public.newsletter_subscribers enable row level security;
create policy "public reads public journal categories" on public.journal_categories for select using (is_public);
create policy "public reads published journal posts" on public.journal_posts for select using (status='published' and published_at is not null and published_at <= now());
create policy "public reads journal tags" on public.journal_tags for select using (true);
create policy "public reads tags for published posts" on public.journal_post_tags for select using (exists (select 1 from public.journal_posts p where p.id=journal_post_id and p.status='published' and p.published_at <= now()));
create policy "public reads authors for published posts" on public.journal_post_authors for select using (exists (select 1 from public.journal_posts p where p.id=journal_post_id and p.status='published' and p.published_at <= now()));
create policy "public reads ventures for published posts" on public.journal_post_ventures for select using (exists (select 1 from public.journal_posts p where p.id=journal_post_id and p.status='published' and p.published_at <= now()));
create policy "public reads issue links for published posts" on public.journal_post_issues for select using (exists (select 1 from public.journal_posts p where p.id=journal_post_id and p.status='published' and p.published_at <= now()));
create policy "public reads published translations" on public.journal_translations for select using (translation_status='published' and (published_at is null or published_at <= now()) and exists (select 1 from public.journal_posts p where p.id=journal_post_id and p.status='published' and p.published_at <= now()));
create policy "authenticated users create story submissions" on public.journal_story_submissions for insert to authenticated with check (submitted_by_profile_id = auth.uid() or submitted_by_profile_id is null);
create policy "users read own story submissions" on public.journal_story_submissions for select to authenticated using (submitted_by_profile_id = auth.uid());
create policy "users update own pending story submissions" on public.journal_story_submissions for update to authenticated using (submitted_by_profile_id=auth.uid() and status='pending') with check (submitted_by_profile_id=auth.uid() and status='pending');
create policy "public can subscribe to newsletter" on public.newsletter_subscribers for insert with check (consent_at is not null and status='active');

insert into public.journal_categories (name,slug,description,display_order,is_public) values ('Mission','mission','Mission updates from Bankrupt to 1 Million.',1,true),('Founder Stories','founder-stories','Founder and rebuilding stories.',2,true),('Visions','visions','Strategic long-form visions.',3,true),('Venture Concepts','venture-concepts','Venture concepts and experiments.',4,true),('Build in Public','build-in-public','Transparent build updates.',5,true),('Lessons','lessons','Lessons learned while rebuilding.',6,true),('Community','community','Community stories.',7,true),('Behind the Scenes','behind-the-scenes','Behind-the-scenes context.',8,true),('Videos','videos','Video-based publications.',9,true) on conflict (slug) do update set name=excluded.name, display_order=excluded.display_order, is_public=excluded.is_public;
insert into public.journal_tags (name,slug,description) values ('Mission','mission','Mission content'),('Build in Public','build-in-public','Build updates'),('Contributors','contributors','Contributor recognition'),('VentureFoundry','venturefoundry','VentureFoundry context') on conflict (slug) do nothing;
insert into public.journal_posts (slug,status,title,subtitle,excerpt,body,content_format,original_language,category_id,is_featured,is_vision_feature,published_at,reading_time_minutes,seo_title,seo_description) values
('why-we-are-building-bankrupt-to-1-million','published','Why We Are Building Bankrupt to 1 Million','A public mission instead of a polished after-story.','Bankrupt to 1 Million exists to document rebuilding honestly and invite useful contributors into the work while it is unfolding.','# Why We Are Building Bankrupt to 1 Million\n\nBankrupt to 1 Million is presented in this repository as a living documentary, community platform and venture story about rebuilding honestly.\n\nThe project is intentionally public: the website points people toward contribution issues, a public impact dashboard and permission-first recognition for founding builders.\n\nThe mission is conservative and simple: create a credible home for transparent founder updates, contribution opportunities and future ventures without pretending the ending is already known.','markdown','en',(select id from public.journal_categories where slug='mission'),true,true,now() - interval '3 days',4,'Why We Are Building Bankrupt to 1 Million','A conservative public introduction to the mission behind Bankrupt to 1 Million.'),
('building-the-website-in-public','published','Building the Website in Public','The product foundation is issue-led and visible.','The current application connects the website, GitHub issue browser, contributor profile flow and impact view into one public build path.','# Building the Website in Public\n\nThe repository already contains routes for the home page, Founding Heroes, contribution issues and an impact dashboard.\n\nThose pieces make the build process visible: contributors can browse synchronized GitHub issues, see implementation context and complete a profile before claiming focused work.\n\nThe Journal extends that same principle into editorial publishing.','markdown','en',(select id from public.journal_categories where slug='build-in-public'),false,false,now() - interval '2 days',3,'Building the Website in Public','How the Bankrupt to 1 Million website is being built in public.'),
('why-every-contributor-deserves-recognition','published','Why Every Contributor Deserves Recognition','Useful work should become part of the public history.','The existing Founding Heroes direction is permission-first: recognize useful work without rankings, points or invented social proof.','# Why Every Contributor Deserves Recognition\n\nThe Founding Heroes page reserves space for real contributor recognition after permission and context are confirmed.\n\nThat matters because early trust is part of the story. Code, design, testing, writing, accessibility and introductions can all shape the foundation.\n\nRecognition should be connected to meaningful contributions, not manufactured status.','markdown','en',(select id from public.journal_categories where slug='community'),false,false,now() - interval '1 day',3,'Why Every Contributor Deserves Recognition','A Journal starter article about permission-first contributor recognition.') on conflict (slug) do nothing;
insert into public.journal_posts (slug,status,title,content_format,original_language,category_id,reading_time_minutes) select slug,'draft',title,'markdown','en',(select id from public.journal_categories where slug=category),4 from (values ('from-rock-bottom-to-a-public-mission','From Rock Bottom to a Public Mission','founder-stories'),('why-we-refuse-to-build-this-journey-alone','Why We Refuse to Build This Journey Alone','mission'),('meet-kevin-and-micha','Meet Kevin and Micha','founder-stories'),('the-architect-and-the-builder','The Architect and the Builder','founder-stories'),('the-vision-behind-venturefoundry','The Vision Behind VentureFoundry','venture-concepts'),('why-adhd-brains-need-the-right-environment','Why ADHD Brains Need the Right Environment','lessons'),('what-we-learned-from-trying-to-do-everything-alone','What We Learned From Trying to Do Everything Alone','lessons'),('our-first-founding-builders','Our First Founding Builders','community'),('the-road-ahead-from-crisis-to-freedom','The Road Ahead: From Crisis to Freedom','visions')) as drafts(slug,title,category) on conflict (slug) do nothing;
insert into public.journal_post_ventures (journal_post_id, venture_slug, venture_name) select id, 'venturefoundry', 'VentureFoundry' from public.journal_posts where slug in ('why-we-are-building-bankrupt-to-1-million','building-the-website-in-public') on conflict do nothing;
