-- Expand journal footage UI translations to all active languages and update open key interpolation

update public.website_translation_keys
set default_text = 'Open footage {number}',
    interpolation_variables = '{"number"}',
    updated_at = now()
where translation_key = 'journal.footage.open';

update public.website_translations wt
set translated_text = 'Open footage {number}',
    updated_at = now()
from public.website_translation_keys k
where wt.translation_key_id = k.id
  and k.translation_key = 'journal.footage.open'
  and wt.language_code = 'en';

with catalog(translation_key, language_code, translated_text) as (
  values
    ('journal.footage.eyebrow','nl','Beelden van de reis'),('journal.footage.title','nl','Beleef het moment zoals het gebeurde.'),('journal.footage.open','nl','Beeld {number} openen'),('journal.footage.close','nl','Viewer sluiten'),('journal.footage.previous','nl','Vorige'),('journal.footage.next','nl','Volgende'),('journal.footage.counter','nl','{current} van {total}'),('journal.footage.alt.image','nl','Evenementfoto {number}'),('journal.footage.alt.video','nl','Evenementvideo {number}'),('journal.footage.loading','nl','Beelden laden…'),('journal.footage.error','nl','Beelden konden niet worden geladen.'),
    ('journal.footage.eyebrow','fr','Images du voyage'),('journal.footage.title','fr','Vivez l''instant tel qu''il s''est passé.'),('journal.footage.open','fr','Ouvrir l''image {number}'),('journal.footage.close','fr','Fermer la visionneuse'),('journal.footage.previous','fr','Précédent'),('journal.footage.next','fr','Suivant'),('journal.footage.counter','fr','{current} sur {total}'),('journal.footage.alt.image','fr','Photo de l''événement {number}'),('journal.footage.alt.video','fr','Vidéo de l''événement {number}'),('journal.footage.loading','fr','Chargement des images…'),('journal.footage.error','fr','Impossible de charger les images.'),
    ('journal.footage.eyebrow','it','Immagini del viaggio'),('journal.footage.title','it','Vivi il momento com''è accaduto.'),('journal.footage.open','it','Apri immagine {number}'),('journal.footage.close','it','Chiudi visualizzatore'),('journal.footage.previous','it','Precedente'),('journal.footage.next','it','Successivo'),('journal.footage.counter','it','{current} di {total}'),('journal.footage.alt.image','it','Foto dell''evento {number}'),('journal.footage.alt.video','it','Video dell''evento {number}'),('journal.footage.loading','it','Caricamento immagini…'),('journal.footage.error','it','Impossibile caricare le immagini.'),
    ('journal.footage.eyebrow','pt','Imagens da jornada'),('journal.footage.title','pt','Viva o momento como aconteceu.'),('journal.footage.open','pt','Abrir imagem {number}'),('journal.footage.close','pt','Fechar visualizador'),('journal.footage.previous','pt','Anterior'),('journal.footage.next','pt','Seguinte'),('journal.footage.counter','pt','{current} de {total}'),('journal.footage.alt.image','pt','Foto do evento {number}'),('journal.footage.alt.video','pt','Vídeo do evento {number}'),('journal.footage.loading','pt','A carregar imagens…'),('journal.footage.error','pt','Não foi possível carregar as imagens.'),
    ('journal.footage.eyebrow','pl','Materiały z podróży'),('journal.footage.title','pl','Zobacz chwilę taką, jaką była.'),('journal.footage.open','pl','Otwórz materiał {number}'),('journal.footage.close','pl','Zamknij podgląd'),('journal.footage.previous','pl','Poprzedni'),('journal.footage.next','pl','Następny'),('journal.footage.counter','pl','{current} z {total}'),('journal.footage.alt.image','pl','Zdjęcie z wydarzenia {number}'),('journal.footage.alt.video','pl','Wideo z wydarzenia {number}'),('journal.footage.loading','pl','Ładowanie materiałów…'),('journal.footage.error','pl','Nie udało się załadować materiałów.'),
    ('journal.footage.eyebrow','ro','Imagini din călătorie'),('journal.footage.title','ro','Trăiește momentul așa cum s-a întâmplat.'),('journal.footage.open','ro','Deschide imaginea {number}'),('journal.footage.close','ro','Închide vizualizatorul'),('journal.footage.previous','ro','Anterior'),('journal.footage.next','ro','Următor'),('journal.footage.counter','ro','{current} din {total}'),('journal.footage.alt.image','ro','Fotografie de la eveniment {number}'),('journal.footage.alt.video','ro','Video de la eveniment {number}'),('journal.footage.loading','ro','Se încarcă imaginile…'),('journal.footage.error','ro','Imaginile nu au putut fi încărcate.'),
    ('journal.footage.eyebrow','uk','Кадри з подорожі'),('journal.footage.title','uk','Побачте момент таким, яким він був.'),('journal.footage.open','uk','Відкрити кадр {number}'),('journal.footage.close','uk','Закрити переглядач'),('journal.footage.previous','uk','Попередній'),('journal.footage.next','uk','Наступний'),('journal.footage.counter','uk','{current} з {total}'),('journal.footage.alt.image','uk','Фото події {number}'),('journal.footage.alt.video','uk','Відео події {number}'),('journal.footage.loading','uk','Завантаження кадрів…'),('journal.footage.error','uk','Не вдалося завантажити кадри.'),
    ('journal.footage.eyebrow','ru','Кадры из путешествия'),('journal.footage.title','ru','Увидьте момент таким, каким он был.'),('journal.footage.open','ru','Открыть кадр {number}'),('journal.footage.close','ru','Закрыть просмотр'),('journal.footage.previous','ru','Предыдущий'),('journal.footage.next','ru','Следующий'),('journal.footage.counter','ru','{current} из {total}'),('journal.footage.alt.image','ru','Фото события {number}'),('journal.footage.alt.video','ru','Видео события {number}'),('journal.footage.loading','ru','Загрузка кадров…'),('journal.footage.error','ru','Не удалось загрузить кадры.'),
    ('journal.footage.eyebrow','sv','Bilder från resan'),('journal.footage.title','sv','Upplev ögonblicket som det var.'),('journal.footage.open','sv','Öppna bild {number}'),('journal.footage.close','sv','Stäng visare'),('journal.footage.previous','sv','Föregående'),('journal.footage.next','sv','Nästa'),('journal.footage.counter','sv','{current} av {total}'),('journal.footage.alt.image','sv','Eventfoto {number}'),('journal.footage.alt.video','sv','Eventvideo {number}'),('journal.footage.loading','sv','Laddar bilder…'),('journal.footage.error','sv','Bilderna kunde inte laddas.'),
    ('journal.footage.eyebrow','no','Bilder fra reisen'),('journal.footage.title','no','Opplev øyeblikket slik det skjedde.'),('journal.footage.open','no','Åpne bilde {number}'),('journal.footage.close','no','Lukk visning'),('journal.footage.previous','no','Forrige'),('journal.footage.next','no','Neste'),('journal.footage.counter','no','{current} av {total}'),('journal.footage.alt.image','no','Hendelsesfoto {number}'),('journal.footage.alt.video','no','Hendelsesvideo {number}'),('journal.footage.loading','no','Laster bilder…'),('journal.footage.error','no','Bildene kunne ikke lastes.'),
    ('journal.footage.eyebrow','da','Billeder fra rejsen'),('journal.footage.title','da','Oplev øjeblikket, som det skete.'),('journal.footage.open','da','Åbn billede {number}'),('journal.footage.close','da','Luk fremviser'),('journal.footage.previous','da','Forrige'),('journal.footage.next','da','Næste'),('journal.footage.counter','da','{current} af {total}'),('journal.footage.alt.image','da','Begivenhedsfoto {number}'),('journal.footage.alt.video','da','Begivenhedsvideo {number}'),('journal.footage.loading','da','Indlæser billeder…'),('journal.footage.error','da','Billederne kunne ikke indlæses.'),
    ('journal.footage.eyebrow','fi','Kuvia matkalta'),('journal.footage.title','fi','Koe hetki sellaisena kuin se tapahtui.'),('journal.footage.open','fi','Avaa kuva {number}'),('journal.footage.close','fi','Sulje katselu'),('journal.footage.previous','fi','Edellinen'),('journal.footage.next','fi','Seuraava'),('journal.footage.counter','fi','{current} / {total}'),('journal.footage.alt.image','fi','Tapahtumakuva {number}'),('journal.footage.alt.video','fi','Tapahtumavideo {number}'),('journal.footage.loading','fi','Ladataan kuvia…'),('journal.footage.error','fi','Kuvia ei voitu ladata.'),
    ('journal.footage.eyebrow','el','Στιγμιότυπα από το ταξίδι'),('journal.footage.title','el','Ζήστε τη στιγμή όπως συνέβη.'),('journal.footage.open','el','Άνοιγμα εικόνας {number}'),('journal.footage.close','el','Κλείσιμο προβολής'),('journal.footage.previous','el','Προηγούμενο'),('journal.footage.next','el','Επόμενο'),('journal.footage.counter','el','{current} από {total}'),('journal.footage.alt.image','el','Φωτογραφία εκδήλωσης {number}'),('journal.footage.alt.video','el','Βίντεο εκδήλωσης {number}'),('journal.footage.loading','el','Φόρτωση εικόνων…'),('journal.footage.error','el','Δεν ήταν δυνατή η φόρτωση των εικόνων.'),
    ('journal.footage.eyebrow','cs','Záběry z cesty'),('journal.footage.title','cs','Prožijte okamžik tak, jak se stal.'),('journal.footage.open','cs','Otevřít záběr {number}'),('journal.footage.close','cs','Zavřít prohlížeč'),('journal.footage.previous','cs','Předchozí'),('journal.footage.next','cs','Další'),('journal.footage.counter','cs','{current} z {total}'),('journal.footage.alt.image','cs','Fotografie z akce {number}'),('journal.footage.alt.video','cs','Video z akce {number}'),('journal.footage.loading','cs','Načítání záběrů…'),('journal.footage.error','cs','Záběry se nepodařilo načíst.'),
    ('journal.footage.eyebrow','sk','Zábery z cesty'),('journal.footage.title','sk','Zažite moment tak, ako sa stal.'),('journal.footage.open','sk','Otvoriť záber {number}'),('journal.footage.close','sk','Zavrieť prehliadač'),('journal.footage.previous','sk','Predchádzajúci'),('journal.footage.next','sk','Ďalší'),('journal.footage.counter','sk','{current} z {total}'),('journal.footage.alt.image','sk','Fotografia z udalosti {number}'),('journal.footage.alt.video','sk','Video z udalosti {number}'),('journal.footage.loading','sk','Načítavanie záberov…'),('journal.footage.error','sk','Zábery sa nepodarilo načítať.'),
    ('journal.footage.eyebrow','sl','Posnetki s poti'),('journal.footage.title','sl','Doživite trenutek, kot se je zgodil.'),('journal.footage.open','sl','Odpri posnetek {number}'),('journal.footage.close','sl','Zapri pregledovalnik'),('journal.footage.previous','sl','Prejšnji'),('journal.footage.next','sl','Naslednji'),('journal.footage.counter','sl','{current} od {total}'),('journal.footage.alt.image','sl','Fotografija dogodka {number}'),('journal.footage.alt.video','sl','Video dogodka {number}'),('journal.footage.loading','sl','Nalaganje posnetkov…'),('journal.footage.error','sl','Posnetkov ni bilo mogoče naložiti.'),
    ('journal.footage.eyebrow','hu','Felvételek az útról'),('journal.footage.title','hu','Éld át a pillanatot úgy, ahogy történt.'),('journal.footage.open','hu','{number}. felvétel megnyitása'),('journal.footage.close','hu','Néző bezárása'),('journal.footage.previous','hu','Előző'),('journal.footage.next','hu','Következő'),('journal.footage.counter','hu','{current} / {total}'),('journal.footage.alt.image','hu','Eseményfotó {number}'),('journal.footage.alt.video','hu','Eseményvideó {number}'),('journal.footage.loading','hu','Felvételek betöltése…'),('journal.footage.error','hu','A felvételek nem tölthetők be.'),
    ('journal.footage.eyebrow','hr','Snimke s putovanja'),('journal.footage.title','hr','Doživite trenutak onako kako se dogodio.'),('journal.footage.open','hr','Otvori snimku {number}'),('journal.footage.close','hr','Zatvori preglednik'),('journal.footage.previous','hr','Prethodno'),('journal.footage.next','hr','Sljedeće'),('journal.footage.counter','hr','{current} od {total}'),('journal.footage.alt.image','hr','Fotografija događaja {number}'),('journal.footage.alt.video','hr','Video događaja {number}'),('journal.footage.loading','hr','Učitavanje snimki…'),('journal.footage.error','hr','Snimke se nisu mogle učitati.'),
    ('journal.footage.eyebrow','sr','Снимци са пута'),('journal.footage.title','sr','Доживите тренутак онако како се догодило.'),('journal.footage.open','sr','Отвори снимак {number}'),('journal.footage.close','sr','Затвори прегледач'),('journal.footage.previous','sr','Претходно'),('journal.footage.next','sr','Следеће'),('journal.footage.counter','sr','{current} од {total}'),('journal.footage.alt.image','sr','Фотографија догађаја {number}'),('journal.footage.alt.video','sr','Видео догађаја {number}'),('journal.footage.loading','sr','Учитавање снимака…'),('journal.footage.error','sr','Снимци се нису могли учитати.'),
    ('journal.footage.eyebrow','bg','Кадри от пътуването'),('journal.footage.title','bg','Преживейте момента така, както се е случил.'),('journal.footage.open','bg','Отвори кадър {number}'),('journal.footage.close','bg','Затвори прегледача'),('journal.footage.previous','bg','Предишен'),('journal.footage.next','bg','Следващ'),('journal.footage.counter','bg','{current} от {total}'),('journal.footage.alt.image','bg','Снимка от събитието {number}'),('journal.footage.alt.video','bg','Видео от събитието {number}'),('journal.footage.loading','bg','Зареждане на кадри…'),('journal.footage.error','bg','Кадрите не можаха да бъдат заредени.'),
    ('journal.footage.eyebrow','lt','Kadrai iš kelionės'),('journal.footage.title','lt','Patirkite akimirką tokią, kokia ji buvo.'),('journal.footage.open','lt','Atidaryti kadrą {number}'),('journal.footage.close','lt','Uždaryti peržiūros langą'),('journal.footage.previous','lt','Ankstesnis'),('journal.footage.next','lt','Kitas'),('journal.footage.counter','lt','{current} iš {total}'),('journal.footage.alt.image','lt','Renginio nuotrauka {number}'),('journal.footage.alt.video','lt','Renginio vaizdo įrašas {number}'),('journal.footage.loading','lt','Įkeliami kadrai…'),('journal.footage.error','lt','Nepavyko įkelti kadrų.'),
    ('journal.footage.eyebrow','lv','Kadri no ceļojuma'),('journal.footage.title','lv','Piedzīvojiet mirkli tādu, kāds tas bija.'),('journal.footage.open','lv','Atvērt kadru {number}'),('journal.footage.close','lv','Aizvērt skatītāju'),('journal.footage.previous','lv','Iepriekšējais'),('journal.footage.next','lv','Nākamais'),('journal.footage.counter','lv','{current} no {total}'),('journal.footage.alt.image','lv','Pasākuma foto {number}'),('journal.footage.alt.video','lv','Pasākuma video {number}'),('journal.footage.loading','lv','Ielādē kadri…'),('journal.footage.error','lv','Kadrus neizdevās ielādēt.'),
    ('journal.footage.eyebrow','et','Reisist pärit kaadrid'),('journal.footage.title','et','Elage hetk üle nii, nagu see toimus.'),('journal.footage.open','et','Ava kaader {number}'),('journal.footage.close','et','Sulge vaatur'),('journal.footage.previous','et','Eelmine'),('journal.footage.next','et','Järgmine'),('journal.footage.counter','et','{current} / {total}'),('journal.footage.alt.image','et','Ürituse foto {number}'),('journal.footage.alt.video','et','Ürituse video {number}'),('journal.footage.loading','et','Kaadrite laadimine…'),('journal.footage.error','et','Kaadreid ei õnnestunud laadida.'),
    ('journal.footage.eyebrow','tr','Yolculuktan görüntüler'),('journal.footage.title','tr','Anı olduğu gibi yaşayın.'),('journal.footage.open','tr','Görüntü {number} aç'),('journal.footage.close','tr','Görüntüleyiciyi kapat'),('journal.footage.previous','tr','Önceki'),('journal.footage.next','tr','Sonraki'),('journal.footage.counter','tr','{current} / {total}'),('journal.footage.alt.image','tr','Etkinlik fotoğrafı {number}'),('journal.footage.alt.video','tr','Etkinlik videosu {number}'),('journal.footage.loading','tr','Görüntüler yükleniyor…'),('journal.footage.error','tr','Görüntüler yüklenemedi.'),
    ('journal.footage.eyebrow','ar','لقطات من الرحلة'),('journal.footage.title','ar','عِش اللحظة كما حدثت.'),('journal.footage.open','ar','فتح اللقطة {number}'),('journal.footage.close','ar','إغلاق العارض'),('journal.footage.previous','ar','السابق'),('journal.footage.next','ar','التالي'),('journal.footage.counter','ar','{current} من {total}'),('journal.footage.alt.image','ar','صورة الحدث {number}'),('journal.footage.alt.video','ar','فيديو الحدث {number}'),('journal.footage.loading','ar','جارٍ تحميل اللقطات…'),('journal.footage.error','ar','تعذر تحميل اللقطات.'),
    ('journal.footage.eyebrow','zh','旅途影像'),('journal.footage.title','zh','重温那一刻的真实模样。'),('journal.footage.open','zh','打开影像 {number}'),('journal.footage.close','zh','关闭查看器'),('journal.footage.previous','zh','上一张'),('journal.footage.next','zh','下一张'),('journal.footage.counter','zh','{current} / {total}'),('journal.footage.alt.image','zh','活动照片 {number}'),('journal.footage.alt.video','zh','活动视频 {number}'),('journal.footage.loading','zh','正在加载影像…'),('journal.footage.error','zh','无法加载影像。'),
    ('journal.footage.eyebrow','hi','यात्रा की तस्वीरें'),('journal.footage.title','hi','पल को वैसा ही देखें जैसा वह हुआ।'),('journal.footage.open','hi','फुटेज {number} खोलें'),('journal.footage.close','hi','व्यूअर बंद करें'),('journal.footage.previous','hi','पिछला'),('journal.footage.next','hi','अगला'),('journal.footage.counter','hi','{current} / {total}'),('journal.footage.alt.image','hi','इवेंट फोटो {number}'),('journal.footage.alt.video','hi','इवेंट वीडियो {number}'),('journal.footage.loading','hi','फुटेज लोड हो रहा है…'),('journal.footage.error','hi','फुटेज लोड नहीं हो सका।'),
    ('journal.footage.open','es','Abrir imagen {number}'),('journal.footage.open','de','Aufnahme {number} öffnen')
), resolved as (
  select k.id as translation_key_id, c.language_code, c.translated_text
  from catalog c
  join public.website_translation_keys k on k.translation_key = c.translation_key
)
insert into public.website_translations
  (translation_key_id, language_code, translated_text, translation_status, translation_source, translated_at, reviewed_at, published_at)
select translation_key_id, language_code, translated_text, 'published', 'manual', now(), now(), now()
from resolved
on conflict (translation_key_id, language_code) do update
set translated_text = excluded.translated_text,
    translation_status = 'published',
    translation_source = 'manual',
    translated_at = now(),
    reviewed_at = now(),
    published_at = now(),
    updated_at = now();

do $$
declare
  rec record;
begin
  if to_regprocedure('private.enqueue_translation_job_expansion(text,uuid,text,jsonb,text)') is not null then
    for rec in
      select id, translation_key, default_text
      from public.website_translation_keys
      where translation_key like 'journal.footage.%'
    loop
      perform private.enqueue_translation_job_expansion(
        'website_key',
        rec.id,
        'en',
        jsonb_build_object('translation_key', rec.translation_key, 'default_text', rec.default_text),
        'journal-footage-v1'
      );
    end loop;
  end if;
end $$;
